// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwgnPqFhAeGDs096UjGWw1444HN5v2qGk',
    appId: '1:570359987310:web:7b3fd8d308d0a5b8e8fa7f',
    messagingSenderId: '570359987310',
    projectId: 'sihapp-312d2',
    authDomain: 'sihapp-312d2.firebaseapp.com',
    storageBucket: 'sihapp-312d2.appspot.com',
    measurementId: 'G-53N7JR7KKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbxZrYRtt5F0IKKKYfIPFcjWw41boJaYA',
    appId: '1:570359987310:android:9e7b63ddbb4b7515e8fa7f',
    messagingSenderId: '570359987310',
    projectId: 'sihapp-312d2',
    storageBucket: 'sihapp-312d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuRbDExufvZ8eiPqg0s15HcHNrXYrU7DM',
    appId: '1:570359987310:ios:d0c56a1b40f8e6f9e8fa7f',
    messagingSenderId: '570359987310',
    projectId: 'sihapp-312d2',
    storageBucket: 'sihapp-312d2.appspot.com',
    androidClientId: '570359987310-6cfuei2t45hitjodmob4hv2cs5nfkbg9.apps.googleusercontent.com',
    iosClientId: '570359987310-l9s7vbu1u2i1eb0ljo14qneuj1jdedil.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuRbDExufvZ8eiPqg0s15HcHNrXYrU7DM',
    appId: '1:570359987310:ios:7f3b0f4ca6f539d8e8fa7f',
    messagingSenderId: '570359987310',
    projectId: 'sihapp-312d2',
    storageBucket: 'sihapp-312d2.appspot.com',
    androidClientId: '570359987310-6cfuei2t45hitjodmob4hv2cs5nfkbg9.apps.googleusercontent.com',
    iosClientId: '570359987310-85fstehfq2pasp6l5lko2895v5gt79av.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih.RunnerTests',
  );
}
